name: ✨ Feature Request
description: Suggest a new feature or enhancement for xScheduler
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail below.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when... / It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Be as detailed as possible.
      placeholder: |
        I would like to see...
        
        Example use case:
        - User clicks...
        - System does...
        - Result is...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: "I also considered... / Another approach could be..."
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Improvement to existing feature
        - UI/UX enhancement
        - Performance optimization
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Critical - Blocking my usage
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / User Story
      description: |
        Describe who would benefit from this feature and how.
        Format: "As a [user type], I want [goal] so that [benefit]"
      placeholder: |
        As a salon owner, I want to...
        This would help me...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
      placeholder: "You can drag & drop images, include links to similar features in other apps, etc."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues/feature requests to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals (appointment scheduling system)
          required: true
        - label: I am willing to test this feature if implemented
          required: false
